# Read the Docs configuration file
version: 2

# Set the OS and Python version
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Build the documentation using Sphinx
sphinx:
  configuration: docs/conf.py

# Specify any Python dependencies required for building the documentation
python:
  install:
    - requirements: docs/requirements.txt
