# Read the Docs configuration file
version: 2

# Set the OS and Python version
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Build formats for both HTML and PDF
formats:
  - html
  - pdf

# Build the documentation using MkDocs
mkdocs:
  configuration: mkdocs.yml

# Specify any Python dependencies required for building the documentation
python:
  install:
    - requirements: docs/requirements.txt

