site_name: ML Copilot Agent
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Installation: installation.md
  - Usage:
      - Overview: usage/overview.md
      - Commands: usage/commands.md
  - Features:
      - Data Preprocessing: features/preprocessing.md
      - Model Training: features/training.md
      - Model Evaluation: features/evaluation.md
      - Plotting: features/plotting.md
      - Custom Instructions: features/custom_instructions.md
  - Configuration: configuration.md
  - Contributing: contributing.md
  - License: license.md
  - FAQ: faq.md

plugins:
  - search
  - pdf-export
